name: Deploy on push
on:
  push:
    branches:
      - trunk

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    if: github.repository_owner == 'woocommerce'
    name: Build and deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: ./build.sh
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
